### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by chiharu05** [chiharu05/protospace-37257#1]
#URL
https://protospace-37257.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@chiharu05 さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるようにしましょう。**
ログアウト時、投稿されたプロトタイプが表示されません
※上記につき、今回動作確認ができなかったログアウト時の挙動は再提出いただいた際に確認させていただきます



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
ご提出いただきありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
